runtime: python312

instance_class: F2
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:q<?nG]]2/8hLK?z-@/yogya-housing-price?unix_socket=/cloudsql/long-setting-426914-j1:us-central1:yogya-housing-price

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
